language: python

python:
  - "3.7.5"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - virtualenv venv
  - sudo apt-get install python-opencv
  - sudo dpkg -L python-opencv
  - sudo apt-get update

install:
  - pip install --upgrade pip
  - pip install opencv-contrib-python
  - pip install pygame
  - pip install numpy
  - pip install imutils
  - pip install argparse
  - sudo apt-get install build-essential
  - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

before_script:
  - git clone https://github.com/vincentianxing/opencv.git
  - git clone https://github.com/opencv/opencv_contrib.git
  - cd opencv
  - mkdir build
  - cd build
  #- cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j4
  - sudo make install
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - echo "OpenCV installed."

script:
  - pytest test.py
  - python testlr.py