language: python

python:
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - virtualenv venv
  - sudo apt-get install python-opencv
  - sudo dpkg -L python-opencv
  - sudo apt-get update

install:
  - pip install --upgrade pip
  - pip install opencv-python

#script:
  #- pytest